package models

import "reflect"

// NewStructForResourceName initializes a struct pointer with a specific name
func NewStructForResourceName(name string) interface{} {
	rStruct := StructForResourceName(name)
	structPtr := reflect.New(reflect.TypeOf(rStruct))
	structPtr.Elem().Set(reflect.ValueOf(rStruct))
	return structPtr.Interface()
}

// SliceForResourceName initializes a slice with the given resource's name
func SliceForResourceName(name string, len int, cap int) interface{} {
	rType := reflect.TypeOf(StructForResourceName(name))
	return reflect.MakeSlice(reflect.SliceOf(rType), len, cap).Interface()
}

// NewSliceForResourceName creates a pointer to a slice pointer
func NewSliceForResourceName(name string, len int, cap int) interface{} {
	rSlice := SliceForResourceName(name, len, cap)
	rSlicePtr := reflect.New(reflect.TypeOf(rSlice))
	rSlicePtr.Elem().Set(reflect.ValueOf(rSlice))
	return rSlicePtr.Interface()
}

// StructForResourceName creates a struct given a resource name
func StructForResourceName(name string) interface{} {
	switch name {
	case "Account":
		return Account{}
	case "ActivityDefinition":
		return ActivityDefinition{}
	case "AdverseEvent":
		return AdverseEvent{}
	case "AllergyIntolerance":
		return AllergyIntolerance{}
	case "Appointment":
		return Appointment{}
	case "AppointmentResponse":
		return AppointmentResponse{}
	case "AuditEvent":
		return AuditEvent{}
	case "Basic":
		return Basic{}
	case "Binary":
		return Binary{}
	case "BiologicallyDerivedProduct":
		return BiologicallyDerivedProduct{}
	case "BodyStructure":
		return BodyStructure{}
	case "Bundle":
		return Bundle{}
	case "CapabilityStatement":
		return CapabilityStatement{}
	case "CarePlan":
		return CarePlan{}
	case "CareTeam":
		return CareTeam{}
	case "CatalogEntry":
		return CatalogEntry{}
	case "ChargeItem":
		return ChargeItem{}
	case "ChargeItemDefinition":
		return ChargeItemDefinition{}
	case "Claim":
		return Claim{}
	case "ClaimResponse":
		return ClaimResponse{}
	case "ClinicalImpression":
		return ClinicalImpression{}
	case "CodeSystem":
		return CodeSystem{}
	case "Communication":
		return Communication{}
	case "CommunicationRequest":
		return CommunicationRequest{}
	case "CompartmentDefinition":
		return CompartmentDefinition{}
	case "Composition":
		return Composition{}
	case "ConceptMap":
		return ConceptMap{}
	case "Condition":
		return Condition{}
	case "Consent":
		return Consent{}
	case "Contract":
		return Contract{}
	case "Coverage":
		return Coverage{}
	case "CoverageEligibilityRequest":
		return CoverageEligibilityRequest{}
	case "CoverageEligibilityResponse":
		return CoverageEligibilityResponse{}
	case "DetectedIssue":
		return DetectedIssue{}
	case "Device":
		return Device{}
	case "DeviceDefinition":
		return DeviceDefinition{}
	case "DeviceMetric":
		return DeviceMetric{}
	case "DeviceRequest":
		return DeviceRequest{}
	case "DeviceUseStatement":
		return DeviceUseStatement{}
	case "DiagnosticReport":
		return DiagnosticReport{}
	case "DocumentManifest":
		return DocumentManifest{}
	case "DocumentReference":
		return DocumentReference{}
	case "EffectEvidenceSynthesis":
		return EffectEvidenceSynthesis{}
	case "Encounter":
		return Encounter{}
	case "Endpoint":
		return Endpoint{}
	case "EnrollmentRequest":
		return EnrollmentRequest{}
	case "EnrollmentResponse":
		return EnrollmentResponse{}
	case "EpisodeOfCare":
		return EpisodeOfCare{}
	case "EventDefinition":
		return EventDefinition{}
	case "Evidence":
		return Evidence{}
	case "EvidenceVariable":
		return EvidenceVariable{}
	case "ExampleScenario":
		return ExampleScenario{}
	case "ExplanationOfBenefit":
		return ExplanationOfBenefit{}
	case "FamilyMemberHistory":
		return FamilyMemberHistory{}
	case "Flag":
		return Flag{}
	case "Goal":
		return Goal{}
	case "GraphDefinition":
		return GraphDefinition{}
	case "Group":
		return Group{}
	case "GuidanceResponse":
		return GuidanceResponse{}
	case "HealthcareService":
		return HealthcareService{}
	case "ImagingStudy":
		return ImagingStudy{}
	case "Immunization":
		return Immunization{}
	case "ImmunizationEvaluation":
		return ImmunizationEvaluation{}
	case "ImmunizationRecommendation":
		return ImmunizationRecommendation{}
	case "ImplementationGuide":
		return ImplementationGuide{}
	case "InsurancePlan":
		return InsurancePlan{}
	case "Invoice":
		return Invoice{}
	case "Library":
		return Library{}
	case "Linkage":
		return Linkage{}
	case "List":
		return List{}
	case "Location":
		return Location{}
	case "Measure":
		return Measure{}
	case "MeasureReport":
		return MeasureReport{}
	case "Media":
		return Media{}
	case "Medication":
		return Medication{}
	case "MedicationAdministration":
		return MedicationAdministration{}
	case "MedicationDispense":
		return MedicationDispense{}
	case "MedicationKnowledge":
		return MedicationKnowledge{}
	case "MedicationRequest":
		return MedicationRequest{}
	case "MedicationStatement":
		return MedicationStatement{}
	case "MedicinalProduct":
		return MedicinalProduct{}
	case "MedicinalProductAuthorization":
		return MedicinalProductAuthorization{}
	case "MedicinalProductContraindication":
		return MedicinalProductContraindication{}
	case "MedicinalProductIndication":
		return MedicinalProductIndication{}
	case "MedicinalProductIngredient":
		return MedicinalProductIngredient{}
	case "MedicinalProductInteraction":
		return MedicinalProductInteraction{}
	case "MedicinalProductManufactured":
		return MedicinalProductManufactured{}
	case "MedicinalProductPackaged":
		return MedicinalProductPackaged{}
	case "MedicinalProductPharmaceutical":
		return MedicinalProductPharmaceutical{}
	case "MedicinalProductUndesirableEffect":
		return MedicinalProductUndesirableEffect{}
	case "MessageDefinition":
		return MessageDefinition{}
	case "MessageHeader":
		return MessageHeader{}
	case "MolecularSequence":
		return MolecularSequence{}
	case "NamingSystem":
		return NamingSystem{}
	case "NutritionOrder":
		return NutritionOrder{}
	case "Observation":
		return Observation{}
	case "ObservationDefinition":
		return ObservationDefinition{}
	case "OperationDefinition":
		return OperationDefinition{}
	case "OperationOutcome":
		return OperationOutcome{}
	case "Organization":
		return Organization{}
	case "OrganizationAffiliation":
		return OrganizationAffiliation{}
	case "Patient":
		return Patient{}
	case "PaymentNotice":
		return PaymentNotice{}
	case "PaymentReconciliation":
		return PaymentReconciliation{}
	case "Person":
		return Person{}
	case "PlanDefinition":
		return PlanDefinition{}
	case "Practitioner":
		return Practitioner{}
	case "PractitionerRole":
		return PractitionerRole{}
	case "Procedure":
		return Procedure{}
	case "Provenance":
		return Provenance{}
	case "Questionnaire":
		return Questionnaire{}
	case "QuestionnaireResponse":
		return QuestionnaireResponse{}
	case "RelatedPerson":
		return RelatedPerson{}
	case "RequestGroup":
		return RequestGroup{}
	case "ResearchDefinition":
		return ResearchDefinition{}
	case "ResearchElementDefinition":
		return ResearchElementDefinition{}
	case "ResearchStudy":
		return ResearchStudy{}
	case "ResearchSubject":
		return ResearchSubject{}
	case "RiskAssessment":
		return RiskAssessment{}
	case "RiskEvidenceSynthesis":
		return RiskEvidenceSynthesis{}
	case "Schedule":
		return Schedule{}
	case "SearchParameter":
		return SearchParameter{}
	case "ServiceRequest":
		return ServiceRequest{}
	case "Slot":
		return Slot{}
	case "Specimen":
		return Specimen{}
	case "SpecimenDefinition":
		return SpecimenDefinition{}
	case "StructureDefinition":
		return StructureDefinition{}
	case "StructureMap":
		return StructureMap{}
	case "Subscription":
		return Subscription{}
	case "Substance":
		return Substance{}
	case "SubstanceNucleicAcid":
		return SubstanceNucleicAcid{}
	case "SubstancePolymer":
		return SubstancePolymer{}
	case "SubstanceProtein":
		return SubstanceProtein{}
	case "SubstanceReferenceInformation":
		return SubstanceReferenceInformation{}
	case "SubstanceSourceMaterial":
		return SubstanceSourceMaterial{}
	case "SubstanceSpecification":
		return SubstanceSpecification{}
	case "SupplyDelivery":
		return SupplyDelivery{}
	case "SupplyRequest":
		return SupplyRequest{}
	case "Task":
		return Task{}
	case "TerminologyCapabilities":
		return TerminologyCapabilities{}
	case "TestReport":
		return TestReport{}
	case "TestScript":
		return TestScript{}
	case "ValueSet":
		return ValueSet{}
	case "VerificationResult":
		return VerificationResult{}
	case "VisionPrescription":
		return VisionPrescription{}

	default:
		return nil
	}
}

// SlicePlusForResourceName initializes a sized slice for a resource name
func SlicePlusForResourceName(name string, len int, cap int) interface{} {
	rType := reflect.TypeOf(StructPlusForResourceName(name))
	return reflect.MakeSlice(reflect.SliceOf(rType), len, cap).Interface()
}

// NewSlicePlusForResourceName initializes a sized slice of pointers
func NewSlicePlusForResourceName(name string, len int, cap int) interface{} {
	rSlice := SlicePlusForResourceName(name, len, cap)
	rSlicePtr := reflect.New(reflect.TypeOf(rSlice))
	rSlicePtr.Elem().Set(reflect.ValueOf(rSlice))
	return rSlicePtr.Interface()
}

// StructPlusForResourceName generates a struct for a resource name
func StructPlusForResourceName(name string) interface{} {
	switch name {
	case "Account":
		return AccountPlus{}
	case "ActivityDefinition":
		return ActivityDefinitionPlus{}
	case "AdverseEvent":
		return AdverseEventPlus{}
	case "AllergyIntolerance":
		return AllergyIntolerancePlus{}
	case "Appointment":
		return AppointmentPlus{}
	case "AppointmentResponse":
		return AppointmentResponsePlus{}
	case "AuditEvent":
		return AuditEventPlus{}
	case "Basic":
		return BasicPlus{}
	case "Binary":
		return BinaryPlus{}
	case "BiologicallyDerivedProduct":
		return BiologicallyDerivedProductPlus{}
	case "BodyStructure":
		return BodyStructurePlus{}
	case "Bundle":
		return BundlePlus{}
	case "CapabilityStatement":
		return CapabilityStatementPlus{}
	case "CarePlan":
		return CarePlanPlus{}
	case "CareTeam":
		return CareTeamPlus{}
	case "CatalogEntry":
		return CatalogEntryPlus{}
	case "ChargeItem":
		return ChargeItemPlus{}
	case "ChargeItemDefinition":
		return ChargeItemDefinitionPlus{}
	case "Claim":
		return ClaimPlus{}
	case "ClaimResponse":
		return ClaimResponsePlus{}
	case "ClinicalImpression":
		return ClinicalImpressionPlus{}
	case "CodeSystem":
		return CodeSystemPlus{}
	case "Communication":
		return CommunicationPlus{}
	case "CommunicationRequest":
		return CommunicationRequestPlus{}
	case "CompartmentDefinition":
		return CompartmentDefinitionPlus{}
	case "Composition":
		return CompositionPlus{}
	case "ConceptMap":
		return ConceptMapPlus{}
	case "Condition":
		return ConditionPlus{}
	case "Consent":
		return ConsentPlus{}
	case "Contract":
		return ContractPlus{}
	case "Coverage":
		return CoveragePlus{}
	case "CoverageEligibilityRequest":
		return CoverageEligibilityRequestPlus{}
	case "CoverageEligibilityResponse":
		return CoverageEligibilityResponsePlus{}
	case "DetectedIssue":
		return DetectedIssuePlus{}
	case "Device":
		return DevicePlus{}
	case "DeviceDefinition":
		return DeviceDefinitionPlus{}
	case "DeviceMetric":
		return DeviceMetricPlus{}
	case "DeviceRequest":
		return DeviceRequestPlus{}
	case "DeviceUseStatement":
		return DeviceUseStatementPlus{}
	case "DiagnosticReport":
		return DiagnosticReportPlus{}
	case "DocumentManifest":
		return DocumentManifestPlus{}
	case "DocumentReference":
		return DocumentReferencePlus{}
	case "EffectEvidenceSynthesis":
		return EffectEvidenceSynthesisPlus{}
	case "Encounter":
		return EncounterPlus{}
	case "Endpoint":
		return EndpointPlus{}
	case "EnrollmentRequest":
		return EnrollmentRequestPlus{}
	case "EnrollmentResponse":
		return EnrollmentResponsePlus{}
	case "EpisodeOfCare":
		return EpisodeOfCarePlus{}
	case "EventDefinition":
		return EventDefinitionPlus{}
	case "Evidence":
		return EvidencePlus{}
	case "EvidenceVariable":
		return EvidenceVariablePlus{}
	case "ExampleScenario":
		return ExampleScenarioPlus{}
	case "ExplanationOfBenefit":
		return ExplanationOfBenefitPlus{}
	case "FamilyMemberHistory":
		return FamilyMemberHistoryPlus{}
	case "Flag":
		return FlagPlus{}
	case "Goal":
		return GoalPlus{}
	case "GraphDefinition":
		return GraphDefinitionPlus{}
	case "Group":
		return GroupPlus{}
	case "GuidanceResponse":
		return GuidanceResponsePlus{}
	case "HealthcareService":
		return HealthcareServicePlus{}
	case "ImagingStudy":
		return ImagingStudyPlus{}
	case "Immunization":
		return ImmunizationPlus{}
	case "ImmunizationEvaluation":
		return ImmunizationEvaluationPlus{}
	case "ImmunizationRecommendation":
		return ImmunizationRecommendationPlus{}
	case "ImplementationGuide":
		return ImplementationGuidePlus{}
	case "InsurancePlan":
		return InsurancePlanPlus{}
	case "Invoice":
		return InvoicePlus{}
	case "Library":
		return LibraryPlus{}
	case "Linkage":
		return LinkagePlus{}
	case "List":
		return ListPlus{}
	case "Location":
		return LocationPlus{}
	case "Measure":
		return MeasurePlus{}
	case "MeasureReport":
		return MeasureReportPlus{}
	case "Media":
		return MediaPlus{}
	case "Medication":
		return MedicationPlus{}
	case "MedicationAdministration":
		return MedicationAdministrationPlus{}
	case "MedicationDispense":
		return MedicationDispensePlus{}
	case "MedicationKnowledge":
		return MedicationKnowledgePlus{}
	case "MedicationRequest":
		return MedicationRequestPlus{}
	case "MedicationStatement":
		return MedicationStatementPlus{}
	case "MedicinalProduct":
		return MedicinalProductPlus{}
	case "MedicinalProductAuthorization":
		return MedicinalProductAuthorizationPlus{}
	case "MedicinalProductContraindication":
		return MedicinalProductContraindicationPlus{}
	case "MedicinalProductIndication":
		return MedicinalProductIndicationPlus{}
	case "MedicinalProductIngredient":
		return MedicinalProductIngredientPlus{}
	case "MedicinalProductInteraction":
		return MedicinalProductInteractionPlus{}
	case "MedicinalProductManufactured":
		return MedicinalProductManufacturedPlus{}
	case "MedicinalProductPackaged":
		return MedicinalProductPackagedPlus{}
	case "MedicinalProductPharmaceutical":
		return MedicinalProductPharmaceuticalPlus{}
	case "MedicinalProductUndesirableEffect":
		return MedicinalProductUndesirableEffectPlus{}
	case "MessageDefinition":
		return MessageDefinitionPlus{}
	case "MessageHeader":
		return MessageHeaderPlus{}
	case "MolecularSequence":
		return MolecularSequencePlus{}
	case "NamingSystem":
		return NamingSystemPlus{}
	case "NutritionOrder":
		return NutritionOrderPlus{}
	case "Observation":
		return ObservationPlus{}
	case "ObservationDefinition":
		return ObservationDefinitionPlus{}
	case "OperationDefinition":
		return OperationDefinitionPlus{}
	case "OperationOutcome":
		return OperationOutcomePlus{}
	case "Organization":
		return OrganizationPlus{}
	case "OrganizationAffiliation":
		return OrganizationAffiliationPlus{}
	case "Patient":
		return PatientPlus{}
	case "PaymentNotice":
		return PaymentNoticePlus{}
	case "PaymentReconciliation":
		return PaymentReconciliationPlus{}
	case "Person":
		return PersonPlus{}
	case "PlanDefinition":
		return PlanDefinitionPlus{}
	case "Practitioner":
		return PractitionerPlus{}
	case "PractitionerRole":
		return PractitionerRolePlus{}
	case "Procedure":
		return ProcedurePlus{}
	case "Provenance":
		return ProvenancePlus{}
	case "Questionnaire":
		return QuestionnairePlus{}
	case "QuestionnaireResponse":
		return QuestionnaireResponsePlus{}
	case "RelatedPerson":
		return RelatedPersonPlus{}
	case "RequestGroup":
		return RequestGroupPlus{}
	case "ResearchDefinition":
		return ResearchDefinitionPlus{}
	case "ResearchElementDefinition":
		return ResearchElementDefinitionPlus{}
	case "ResearchStudy":
		return ResearchStudyPlus{}
	case "ResearchSubject":
		return ResearchSubjectPlus{}
	case "RiskAssessment":
		return RiskAssessmentPlus{}
	case "RiskEvidenceSynthesis":
		return RiskEvidenceSynthesisPlus{}
	case "Schedule":
		return SchedulePlus{}
	case "SearchParameter":
		return SearchParameterPlus{}
	case "ServiceRequest":
		return ServiceRequestPlus{}
	case "Slot":
		return SlotPlus{}
	case "Specimen":
		return SpecimenPlus{}
	case "SpecimenDefinition":
		return SpecimenDefinitionPlus{}
	case "StructureDefinition":
		return StructureDefinitionPlus{}
	case "StructureMap":
		return StructureMapPlus{}
	case "Subscription":
		return SubscriptionPlus{}
	case "Substance":
		return SubstancePlus{}
	case "SubstanceNucleicAcid":
		return SubstanceNucleicAcidPlus{}
	case "SubstancePolymer":
		return SubstancePolymerPlus{}
	case "SubstanceProtein":
		return SubstanceProteinPlus{}
	case "SubstanceReferenceInformation":
		return SubstanceReferenceInformationPlus{}
	case "SubstanceSourceMaterial":
		return SubstanceSourceMaterialPlus{}
	case "SubstanceSpecification":
		return SubstanceSpecificationPlus{}
	case "SupplyDelivery":
		return SupplyDeliveryPlus{}
	case "SupplyRequest":
		return SupplyRequestPlus{}
	case "Task":
		return TaskPlus{}
	case "TerminologyCapabilities":
		return TerminologyCapabilitiesPlus{}
	case "TestReport":
		return TestReportPlus{}
	case "TestScript":
		return TestScriptPlus{}
	case "ValueSet":
		return ValueSetPlus{}
	case "VerificationResult":
		return VerificationResultPlus{}
	case "VisionPrescription":
		return VisionPrescriptionPlus{}

	default:
		return nil
	}
}

// PluralizeLowerResourceName generates plural resource names
func PluralizeLowerResourceName(name string) string {
	switch name {
	case "Account":
		return "accounts"
	case "ActivityDefinition":
		return "activitydefinitions"
	case "AdverseEvent":
		return "adverseevents"
	case "AllergyIntolerance":
		return "allergyintolerances"
	case "Appointment":
		return "appointments"
	case "AppointmentResponse":
		return "appointmentresponses"
	case "AuditEvent":
		return "auditevents"
	case "Basic":
		return "basics"
	case "Binary":
		return "binaries"
	case "BiologicallyDerivedProduct":
		return "biologicallyderivedproducts"
	case "BodyStructure":
		return "bodystructures"
	case "Bundle":
		return "bundles"
	case "CapabilityStatement":
		return "capabilitystatements"
	case "CarePlan":
		return "careplans"
	case "CareTeam":
		return "careteams"
	case "CatalogEntry":
		return "catalogentries"
	case "ChargeItem":
		return "chargeitems"
	case "ChargeItemDefinition":
		return "chargeitemdefinitions"
	case "Claim":
		return "claims"
	case "ClaimResponse":
		return "claimresponses"
	case "ClinicalImpression":
		return "clinicalimpressions"
	case "CodeSystem":
		return "codesystems"
	case "Communication":
		return "communications"
	case "CommunicationRequest":
		return "communicationrequests"
	case "CompartmentDefinition":
		return "compartmentdefinitions"
	case "Composition":
		return "compositions"
	case "ConceptMap":
		return "conceptmaps"
	case "Condition":
		return "conditions"
	case "Consent":
		return "consents"
	case "Contract":
		return "contracts"
	case "Coverage":
		return "coverages"
	case "CoverageEligibilityRequest":
		return "coverageeligibilityrequests"
	case "CoverageEligibilityResponse":
		return "coverageeligibilityresponses"
	case "DetectedIssue":
		return "detectedissues"
	case "Device":
		return "devices"
	case "DeviceDefinition":
		return "devicedefinitions"
	case "DeviceMetric":
		return "devicemetrics"
	case "DeviceRequest":
		return "devicerequests"
	case "DeviceUseStatement":
		return "deviceusestatements"
	case "DiagnosticReport":
		return "diagnosticreports"
	case "DocumentManifest":
		return "documentmanifests"
	case "DocumentReference":
		return "documentreferences"
	case "EffectEvidenceSynthesis":
		return "effectevidencesyntheses"
	case "Encounter":
		return "encounters"
	case "Endpoint":
		return "endpoints"
	case "EnrollmentRequest":
		return "enrollmentrequests"
	case "EnrollmentResponse":
		return "enrollmentresponses"
	case "EpisodeOfCare":
		return "episodeofcares"
	case "EventDefinition":
		return "eventdefinitions"
	case "Evidence":
		return "evidences"
	case "EvidenceVariable":
		return "evidencevariables"
	case "ExampleScenario":
		return "examplescenarios"
	case "ExplanationOfBenefit":
		return "explanationofbenefits"
	case "FamilyMemberHistory":
		return "familymemberhistories"
	case "Flag":
		return "flags"
	case "Goal":
		return "goals"
	case "GraphDefinition":
		return "graphdefinitions"
	case "Group":
		return "groups"
	case "GuidanceResponse":
		return "guidanceresponses"
	case "HealthcareService":
		return "healthcareservices"
	case "ImagingStudy":
		return "imagingstudies"
	case "Immunization":
		return "immunizations"
	case "ImmunizationEvaluation":
		return "immunizationevaluations"
	case "ImmunizationRecommendation":
		return "immunizationrecommendations"
	case "ImplementationGuide":
		return "implementationguides"
	case "InsurancePlan":
		return "insuranceplans"
	case "Invoice":
		return "invoices"
	case "Library":
		return "libraries"
	case "Linkage":
		return "linkages"
	case "List":
		return "lists"
	case "Location":
		return "locations"
	case "Measure":
		return "measures"
	case "MeasureReport":
		return "measurereports"
	case "Media":
		return "media"
	case "Medication":
		return "medications"
	case "MedicationAdministration":
		return "medicationadministrations"
	case "MedicationDispense":
		return "medicationdispenses"
	case "MedicationKnowledge":
		return "medicationknowledges"
	case "MedicationRequest":
		return "medicationrequests"
	case "MedicationStatement":
		return "medicationstatements"
	case "MedicinalProduct":
		return "medicinalproducts"
	case "MedicinalProductAuthorization":
		return "medicinalproductauthorizations"
	case "MedicinalProductContraindication":
		return "medicinalproductcontraindications"
	case "MedicinalProductIndication":
		return "medicinalproductindications"
	case "MedicinalProductIngredient":
		return "medicinalproductingredients"
	case "MedicinalProductInteraction":
		return "medicinalproductinteractions"
	case "MedicinalProductManufactured":
		return "medicinalproductmanufactureds"
	case "MedicinalProductPackaged":
		return "medicinalproductpackageds"
	case "MedicinalProductPharmaceutical":
		return "medicinalproductpharmaceuticals"
	case "MedicinalProductUndesirableEffect":
		return "medicinalproductundesirableeffects"
	case "MessageDefinition":
		return "messagedefinitions"
	case "MessageHeader":
		return "messageheaders"
	case "MolecularSequence":
		return "molecularsequences"
	case "NamingSystem":
		return "namingsystems"
	case "NutritionOrder":
		return "nutritionorders"
	case "Observation":
		return "observations"
	case "ObservationDefinition":
		return "observationdefinitions"
	case "OperationDefinition":
		return "operationdefinitions"
	case "OperationOutcome":
		return "operationoutcomes"
	case "Organization":
		return "organizations"
	case "OrganizationAffiliation":
		return "organizationaffiliations"
	case "Patient":
		return "patients"
	case "PaymentNotice":
		return "paymentnotices"
	case "PaymentReconciliation":
		return "paymentreconciliations"
	case "Person":
		return "people"
	case "PlanDefinition":
		return "plandefinitions"
	case "Practitioner":
		return "practitioners"
	case "PractitionerRole":
		return "practitionerroles"
	case "Procedure":
		return "procedures"
	case "Provenance":
		return "provenances"
	case "Questionnaire":
		return "questionnaires"
	case "QuestionnaireResponse":
		return "questionnaireresponses"
	case "RelatedPerson":
		return "relatedpeople"
	case "RequestGroup":
		return "requestgroups"
	case "ResearchDefinition":
		return "researchdefinitions"
	case "ResearchElementDefinition":
		return "researchelementdefinitions"
	case "ResearchStudy":
		return "researchstudies"
	case "ResearchSubject":
		return "researchsubjects"
	case "RiskAssessment":
		return "riskassessments"
	case "RiskEvidenceSynthesis":
		return "riskevidencesyntheses"
	case "Schedule":
		return "schedules"
	case "SearchParameter":
		return "searchparameters"
	case "ServiceRequest":
		return "servicerequests"
	case "Slot":
		return "slots"
	case "Specimen":
		return "specimen"
	case "SpecimenDefinition":
		return "specimendefinitions"
	case "StructureDefinition":
		return "structuredefinitions"
	case "StructureMap":
		return "structuremaps"
	case "Subscription":
		return "subscriptions"
	case "Substance":
		return "substances"
	case "SubstanceNucleicAcid":
		return "substancenucleicacids"
	case "SubstancePolymer":
		return "substancepolymers"
	case "SubstanceProtein":
		return "substanceproteins"
	case "SubstanceReferenceInformation":
		return "substancereferenceinformations"
	case "SubstanceSourceMaterial":
		return "substancesourcematerials"
	case "SubstanceSpecification":
		return "substancespecifications"
	case "SupplyDelivery":
		return "supplydeliveries"
	case "SupplyRequest":
		return "supplyrequests"
	case "Task":
		return "tasks"
	case "TerminologyCapabilities":
		return "terminologycapabilities"
	case "TestReport":
		return "testreports"
	case "TestScript":
		return "testscripts"
	case "ValueSet":
		return "valuesets"
	case "VerificationResult":
		return "verificationresults"
	case "VisionPrescription":
		return "visionprescriptions"

	default:
		return ""
	}
}
